version: "3.9"
services:
  wildfly_examples:
    image: examples/wildfly:1.0-SNAPSHOT
    container_name: examples.wildfly
    ports:
      - 8443:8443 # <port hosta>:<port kontenera>
      - 8787:8787
      - 8080:8080/tcp
      - 9990:9990/tcp
      - 4447:4447
    volumes:
      # zamapowanie katalogu hosta na katalog w kontenerze
      - ./wildfly/deployments:/opt/jboss/wildfly/standalone/deployments
